package com.company.kassa.exceptions;

public enum ErrorCode {

    ENTITY_NOT_FOUND,

    UN_AUTHORIZED,
    MISSING_REQUIRED_FIELD,
    VALIDATION_ERROR,
    PARAMETER_NOT_FOUND,
    FIELD_VALUE_UNIQUE,
    REQUIRED_FIELD,
    VALUE_DID_NOT_MATCH,
    USERNAME_NOT_FOUND,


}
